apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook #siempre hacia argo
  namespace: argocd
spec:
  source:
    path: 'guestbook'
    repoURL: https://github.com/gvillablanca/ArgoProject.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-argopj #a que ns debe ir porque esta es la aplicacion que desplegare
  project: default