apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  destination:
    namespace: test-argopj
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    path: 'guestbook'
    targetRevision: HEAD
  project: test-argopj